name: 'DOCKER NODE BUILD AND PUBLISH'
description: 'Builds and publishes a docker image for a NODEJS project'
inputs:
  username:
    description: 'Docker Hub Username'
    required: true
  password:
    description: 'Docker Hub Password'
    required: true
  name:
    description: 'Product Name'
    required: true
  production:
    description: 'Is this a production build?'
    type: boolean
    required: true
    default: true
runs:
  using: "composite"
  steps:
  - name: Checkout
    uses: actions/checkout@main
    with:
      repository: 'judahh/dockerBuildAndPublish'
      path: docker
  - name: Show Folder Contents 1
    run: ls
    shell: bash
  - name: Show Folder Contents 2
    run: ls ..
    shell: bash
  - name: Show Folder Contents 3
    run: ls ../..
    shell: bash
  - id: serviceName
    uses: ASzc/change-string-case-action@v2
    with:
      string: ${{ inputs.name }}
  - name: Login to Docker Hub
    uses: docker/login-action@master
    with:
      username: ${{ inputs.username }}
      password: ${{ inputs.password }}

  - name: Set up Docker Buildx
    id: buildx
    uses: docker/setup-buildx-action@v1

  - name: Build and push PRODUCT
    id: docker_build_product
    uses: docker/build-push-action@v2
    with:
      context: ./
      file: Dockerfile
      push: true
      tags: ${{ inputs.username }}/${{ inputs.name }}${{ inputs.production && '' || '-s'}}:latest
      build-args: |
        SERVICE_NAME=${{ steps.serviceName.outputs.uppercase }}
        PROJECT_ENV=${{ inputs.production && 'production' || 'staging' }}


